### ISSUE TITLE
JS Failure on Email Submission

### ISSUE THREAD

**Issue by patrickjennings** [uicardiodev/hugo-sodium-theme#2]
I am unable to submit an email through the contact section due to the onclick handler on the following line:

https://github.com/uicardiodev/hugo-sodium-theme/blob/e89f13a2ff4d13a37db2c29e55d8a0d915f1d552/static/js/script.js#L59

Using the prop function instead of attr will fix the issue.

**Comment by heyarviind** [comment]
Fixed, Thanks
